### ISSUE TITLE
When using remainder as latest result it asks for base number

### ISSUE THREAD

**Issue by sammyj48** [Tyopo131/Calculator-2#5]
When I pressed 'R' to use remainder as my latest result, it still asked me to enter the base number when I had a chosen subtract mode from the calculator.  It may happen in any mode, I don't know.

**Comment by Tyopo131** [comment]
Actually, it happens in any mode not just ones that ask for remainder or result. It only happens when your latest result is 0. This is because I used NULL, not knowing that NULL just means 0. If someone could make a pull request to fix this I would greatly appreciate it.

**Comment by Tyopo131** [comment]
Sadly I cant find a way to fix it. It requires detecting an unititialised double variable.

**Comment by Tyopo131** [comment]
Fixed it yay! Just added a global variable (`bool SUM_IN_PROGRESS`) to track whether the user chose A in `exitchoice(double round)`

Oh yes I did remember to set it back to false when the user chooses C

It's because I used NULL when NULL is 0.
